### ISSUE TITLE
Should be called "cargo-wasm"

### ISSUE THREAD

**Issue by lachlansneff** [mgattozzi/cargo-wa#2]
Honestly, "wa" is a pretty dumb name. Yes, I know it stands for WebAssembly, but wasm is a more accepted shortened version.

**Comment by mgattozzi** [comment]
cargo-wasm was taken. I wanted to keep it as wasm. See [here](https://github.com/lord/cargo-wasm) it was abandoned for wargo.

**Comment by durka** [comment]
Maybe they'd be willing to give up the crates.io name since it was abandoned?

**Comment by lachlansneff** [comment]
Asked the owner of `cargo-wa` if he'd be willing to give it up. He graciously did. 
Here's the text of the response:
```
Sure! @mgattozzi on github should have an invite to the project on crates.io, feel free to delete whatever is currently there! (Although plz remove my name from the project if you do update it)
```

**Comment by mgattozzi** [comment]
Appreciate you going and asking @lachlansneff. I'll work on migrating stuff over when I get the chance.
